spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  access:
    key: ${ACCESS_KEY}
  refresh:
    key: ${REFRESH_KEY}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG

# Настройки для Flyway
flyway:
  baseline-on-migrate: true
  locations: classpath:db/migration

  #Flyway - это инструмент управления базой данных,
  #  который обеспечивает контроль версий и миграции баз данных.
  # Он позволяет разработчикам эффективно управлять изменениями схемы базы данных и обновлять ее до текущей версии.
  #
  #Основные возможности Flyway включают:
  #
  #Контроль версий базы данных: Flyway позволяет определить изменения в базе данных в виде миграций,
  #каждая из которых имеет уникальный идентификатор версии. Это позволяет отслеживать,
  # какие миграции были применены, а какие нет.
  #
  #Автоматическое применение миграций: Flyway автоматически применяет новые миграции при запуске приложения.
  # Это упрощает процесс обновления базы данных при развертывании новых версий приложения.
  #
  #Интеграция с различными СУБД: Flyway поддерживает различные системы управления базами данных,
  # такие как MySQL, PostgreSQL, Oracle, SQL Server и другие.
  #
  #Простота использования: Он предоставляет простой и интуитивно понятный способ
  #управления миграциями баз данных с минимальным вмешательством разработчика.
