spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    username: beauty-booking@gmx.net  # Ваш адрес электронной почты GMX
    password: Qwerty007!     # Ваш пароль для электронной почты GMX
    host: smtp.gmx.net   # SMTP-сервер
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  access:
    key: "X30INcpL2Yzf80ArITEdwLegdAFT2dkeq1hxlR7waOk="
  refresh:
    key: "u1vxX56P6a-4tWS2RLt0qIG9yF8DbW6d1pv4JUQI-dk="

logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG

# Настройки для Flyway
flyway:
  baseline-on-migrate: true
  locations: classpath:db/migration